title: Computational actuarial science with R
description: Workshop of the 21<sup>st</sup> International Congress on Insurance: Mathematics and Economics (IME 2017)
theme: jekyll-theme-cayman
show_downloads: "true"
